# Generated by Django 5.0 on 2024-05-06 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_fooddonation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50, unique=True)),
                ('organization_license', models.ImageField(blank=True, upload_to='organization/license')),
                ('chairman_name', models.CharField(default='', max_length=255)),
                ('registered_address', models.TextField(default='', max_length=1024)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.userprofile')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Volunteer',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('joined_at', models.DateTimeField(auto_now_add=True)),
        #         ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_list', to='organization.event')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profiles', to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'unique_together': {('user', 'event')},
        #     },
        # ),
        # migrations.AddField(
        #     model_name='event',
        #     name='volunteers',
        #     field=models.ManyToManyField(related_name='volunteered_events', through='organization.Volunteer', to=settings.AUTH_USER_MODEL),
        # ),
    ]
