# Generated by Django 5.0 on 2024-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_organization_name_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='chairman_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='registered_address',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
