# Generated by Django 5.0 on 2024-05-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_license',
            field=models.ImageField(blank=True, upload_to='organization/license'),
        ),
    ]
