# Generated by Django 5.0 on 2024-05-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_organization_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='phone_number',
        ),
    ]
