# Generated by Django 5.0 on 2024-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_event_content_type_remove_event_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
