# Generated by Django 5.0 on 2024-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_volunteer_event_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteer_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
