# Generated by Django 5.0 on 2024-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_event_volunteer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='volunteer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
