# Generated by Django 5.0 on 2024-05-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_event_latitude_alter_event_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
