# Generated by Django 5.0 on 2024-05-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_alter_event_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='volunteer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
