# Generated by Django 5.0 on 2024-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_event_volunteer_event_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
