# Generated by Django 5.0 on 2024-05-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fooddonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodDonation',
        ),
    ]
