# Generated by Django 5.0 on 2024-05-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_fooddonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_donor', models.CharField(max_length=50)),
                ('food_type', models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('NON-VEGETARIAN', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], max_length=50)),
                ('perishability', models.CharField(choices=[('PERISHABLE', 'Perishable'), ('NON-PERISHABLE', 'Non-Perishable')], max_length=50)),
                ('delivery_method', models.CharField(choices=[('PICK-UP', 'Pick-Up'), ('DROP', 'Drop')], max_length=50)),
                ('quantity', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
