# Generated by Django 5.0 on 2024-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fooddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='scheduled_date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='scheduled_time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
